#docker run --name program -v ./:/data -p 3389:3389 golang:alpine3.20
#sudo docker run --name mysql9  -v ./mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -p 3306:3306  mysql:9.1.0
name: transervicex
services:
  transervice:
    container_name: transervice
    volumes:
      - ./:/data
    ports:
      - 8192:2147
    environment:
      - TOKEN=Ll3eVegZvHU4dB0JrEB8Ee6hGHgE5ZwUDdFeuzXrCM0
      - SQLSERVICE=192.168.1.9:3306
    image: zhangyiming748/transervice
    restart: always