#docker run --name program -v ./:/data -p 3389:3389 golang:alpine3.20
#sudo docker run --name mysql9  -v ./mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=123456 -p 3306:3306  mysql:9.1.0
name: deeplx
services:
  golang:
    container_name: program
    volumes:
      - ./:/data
    ports:
      - 8192:8192
    environment:
      - TOKEN=
    build:
      context: .
      tags:
        - gin:local
      dockerfile: dockerfile
    restart: always